[project]
name = "my-avs"
version = "0.1.0"
description = "Default Hourglass AVS with minimal settings."

[env.devnet]
nemesis_contract_address = "0x123..."
chain_image = "ghcr.io/foundry-rs/foundry:latest"
chain_args = ["--chain-id", "31337", "--block-time", "3", "--gas-price", "0", "--base-fee", "0"]

[release]
avs_logic_image_tag = "some-org/avs-logic:v0.1"
push_image = false

[log]
level = "debug"

[operator]
image = "eigen/ponos-client:v1.0"
keys = ["ac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80","2a871d0798f97d79848a013d4936a73bf4cc922c825d33c1cf7073dff6d409c6"] # Default Anvil keys (index 0 and 9)
total_stake = "1000ETH"

[[operator.bls.keystores]]
path = "keystores/operator1.keystore.json"
password = "password..."

[[operator.bls.keystores]]
path = "keystores/operator2.keystore.json"
password = "password..."

[operator.allocations]
strategies = ["0xf951e335afb289353dc249e82926178eac7ded78"]
task-executors = ["300000000000000000"]
aggregators    = ["250000000000000000"]

[operatorset_aliases]
task_execution = "task-executors"
aggregation = "aggregators"

[operatorsets.task-executors]
operator_set_id = 0
description = "Operators responsible for executing tasks."
rpc_endpoint = "http://localhost:8546"
avs = "0xAVS..."
submit_wallet = "59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d"

[operatorsets.task-executors.operators]
operator_keys = ["ac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"]
minimum_required_stake_weight = ["1000ETH"]

[operatorsets.aggregators.operators]
operator_keys = ["ac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"]
minimum_required_stake_weight = ["1000ETH"]

[operatorsets.aggregators]
operator_set_id = 1
description = "Operators responsible for signature aggregation and submission."
rpc_endpoint = "http://localhost:8547"
avs = "0xAVS..."
submit_wallet = "59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d"