services:
  devkit-devnet:
    image: ghcr.io/foundry-rs/foundry:nightly-1ae64e38a1c69bda45343947875f7c86bad00038
    volumes:
     - ./contracts_deployed_anvil_state/state.json:/anvil/state.json
    entrypoint: anvil
    command: "--host 0.0.0.0 --load-state /anvil/state.json ${ANVIL_ARGS}"
    ports:
      - "8545:8545"