[keys]
account1 = "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"
pendingadmin = "0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d"

[[permissions.set_appointee]]
account = "account1"
appointee = "0xappointeeaddress"
target = "0xtarget..."
selector = "0x12345678"

[[permissions.set_appointee]]
account = "account1"
appointee = "0xappointeeaddress"
target = "0xtarget..."
selector = "0xdeadbeef"

[[permissions.add_pending_admin]]
account = "account1"
pending_admin = "0xpendingadminaddress"

[[permissions.accept_admin]]
account = "pendingadmin"

[[permissions.remove_admin]]
account = "account1"
admin = "0xpendingadminaddress"

[[permissions.remove_appointee]]
account = "account1"
appointee = "0xappointeeaddress"
target = "0xtarget..."
selector = "0xdeadbeef"