architectures:
  task:
    languages:
      go:
        baseUrl: "https://github.com/Layr-Labs/hourglass-avs-template"
        version: "66f52f5eb803ad586e5167836a494748c6f68f55"
      ts:
        baseUrl: ""
        version: ""
      rust:
        baseUrl: ""
        version: ""
