architectures:
  task:
    languages:
      go:
        template: "https://github.com/Layr-Labs/hourglass-avs-template/tree/nova/hourglass_devkit_devnet"
      ts:
        template: ""
      rust:
        template: ""
    contracts:
      languages:
        solidity:
          template: "https://github.com/Layr-Labs/hourglass-contracts-template/tree/nova/hourglass_devkit_template"
        vyper:
          template: ""
  hello-world-avs:
    languages:
      go:
        template: "https://github.com/Layr-Labs/hello-world-avs"
      ts:
        template: ""
      rust:
        template: ""
