architectures:
  task:
    languages:
      go:
        baseUrl: "https://github.com/Layr-Labs/hourglass-avs-template"
        version: "v0.0.4"
      ts:
        baseUrl: ""
        version: ""
      rust:
        baseUrl: ""
        version: ""
    contracts:
      languages:
        solidity:
          baseUrl: "https://github.com/Layr-Labs/hourglass-contracts-template"
          version: "master"
        vyper:
          baseUrl: ""
          version: ""
  hello-world-avs:
    languages:
      go:
        baseUrl: "https://github.com/Layr-Labs/hello-world-avs"
        version: "main"
      ts:
        baseUrl: ""
        version: ""
      rust:
        baseUrl: ""
        version: ""
