architectures:
  task:
    languages:
      go:
        baseUrl: "https://github.com/Layr-Labs/hourglass-avs-template"
        version: "release/l1-l2-support"
      ts:
        baseUrl: ""
        version: ""
      rust:
        baseUrl: ""
        version: ""
