# Devnet context to be used for local deployments against Anvil chain
version: 0.0.1
context:
  # Name of the context
  name: "devnet"
  # Chains available to this context
  chains:
    l1: 
      chain_id: 31337
      rpc_url: "http://localhost:8545"
      fork:
        block: 22475020
        url: "https://eth.llamarpc.com"
    l2:
      chain_id: 31337
      rpc_url: "http://localhost:8545"
      fork:
        block: 22475020
        url: "https://eth.llamarpc.com"
  # All key material (BLS and ECDSA) within this file should be used for local testing ONLY
  # ECDSA keys used are from Anvil's private key set
  # BLS keystores are deterministically pre-generated and embedded. These are NOT derived from a secure seed
  # Available private keys for deploying
  deployer_private_key: "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80" # Anvil Private Key 0
  app_private_key: "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80" # Anvil Private Key 0
  # List of Operators and their private keys / stake details
  operators:
    - address: "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
      ecdsa_key: "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80" # Anvil Private Key 0
      bls_keystore_path: "keystores/operator1.keystore.json"
      bls_keystore_password: "testpass"
      stake: "1000ETH"
    - address: "0x70997970C51812dc3A010C7d01b50e0d17dc79C8"
      ecdsa_key: "0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d" # Anvil Private Key 1
      bls_keystore_path: "keystores/operator2.keystore.json"
      bls_keystore_password: "testpass"
      stake: "1000ETH"
    - address: "0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC"
      ecdsa_key: "0x5de4111afa1a4b94908f83103eb1f1706367c2e68ca870fc3fb9a804cdab365a" # Anvil Private Key 2
      bls_keystore_path: "keystores/operator3.keystore.json"
      bls_keystore_password: "testpass"
      stake: "1000ETH"
    - address: "0x90F79bf6EB2c4f870365E785982E1f101E93b906"
      ecdsa_key: "0x7c852118294e51e653712a81e05800f419141751be58f605c371e15141b007a6" # Anvil Private Key 3
      bls_keystore_path: "keystores/operator4.keystore.json"
      bls_keystore_password: "testpass"
      stake: "1000ETH"
    - address: "0x15d34AAf54267DB7D7c367839AAf71A00a2C6A65"
      ecdsa_key: "0x47e179ec197488593b187f80a00eb0da91f1b9d0b13f8733639f19c30a34926a" # Anvil Private Key 4
      bls_keystore_path: "keystores/operator5.keystore.json"
      bls_keystore_password: "testpass"
      stake: "1000ETH"
  # AVS configuration
  avs:
    address: "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
    avs_private_key: "0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80" # Anvil Private Key 0
    metadata_url: "https://my-org.com/avs/metadata.json"
    registrar_address: "0x0123456789abcdef0123456789ABCDEF01234567"
