[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

remappings = [
    "@openzeppelin/=lib/eigenlayer-contracts/lib/openzeppelin-contracts-v4.9.0/",
    "@eigenlayer-contracts/=lib/eigenlayer-contracts/"
]
solc_version = '0.8.27'
fs_permissions = [{ access = "read-write", path = "./" }]
 via_ir = false
# Whether or not to enable the Solidity optimizer.
optimizer = true
optimizer_runs = 200