services:
  devkit-devnet:
    image: ${FOUNDRY_IMAGE}
    container_name: ${AVS_CONTAINER_NAME} 
    volumes:
      - "${STATE_PATH}:/anvil/state.json"
    entrypoint: anvil
    command: "--host 0.0.0.0  ${ANVIL_ARGS}"
    ports:
      - "${DEVNET_PORT}:8545"
