name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches: ["**"]

env:
  GOPRIVATE: github.com/Layr-Labs/*

jobs:
  Test:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout devkit-cli
        uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.23'
      - name: Build
        env:
          HOURGLASS_TOKEN: ${{ secrets.HOURGLASS_TOKEN }}
        run: |
          git config --global url."https://${HOURGLASS_TOKEN}@github.com/".insteadOf "https://github.com/"

          go mod tidy
          make build
