name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main  

jobs:
  Test:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout devkit-cli
        uses: actions/checkout@v4

      - name: Checkout hourglass-monorepo
        uses: actions/checkout@v4
        with:
          repository: Layr-Labs/hourglass-monorepo
          path: external/hourglass-monorepo

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Replace module and tidy
        run: |
          go mod edit -replace=github.com/Layr-Labs/hourglass-monorepo=./external/hourglass-monorepo
          go mod tidy

      - name: Build
        run: make build
