name: Devkit E2E Test

on:
  push:
    branches: [main]
  pull_request:
    branches: ["**"]

env:
  FOUNDRY_PROFILE: ci
  GOPRIVATE: github.com/Layr-Labs/*
  L1_FORK_URL: ${{ secrets.L1_FORK_URL }}
  L2_FORK_URL: ${{ secrets.L2_FORK_URL }}

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      - name: Authenticate Go to GitHub private repos
        run: |
          git config --global url."https://${{ secrets.HOURGLASS_TOKEN }}:x-oauth-basic@github.com/".insteadOf "https://github.com/"
          echo "machine github.com login ${{ secrets.HOURGLASS_TOKEN }}" > ~/.netrc

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: stable

      - name: Install devkit CLI
        run: make install

      - name: Add ~/bin to PATH
        run: echo "$HOME/bin" >> $GITHUB_PATH

      - name: Run devkit avs create
        run: devkit avs create my-awesome-avs

      - name: Verify AVS project created
        run: |
          if [ ! -f "./my-awesome-avs/config/config.yaml" ]; then
            echo "❌ AVS project config/config.yaml not found!"
            exit 1
          fi
          echo "✅ AVS project created successfully at ${GITHUB_WORKSPACE}/my-awesome-avs/"

      - name: Run devkit avs build
        env:
            DOCKER_BUILDKIT: 1
        run: |
          eval "$(ssh-agent -s)"
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | ssh-add -
          mkdir -p ~/.ssh
          ssh-keyscan github.com >> ~/.ssh/known_hosts

          cd ./my-awesome-avs/
          devkit avs build

      - name: Start devnet
        run: |
          cd ./my-awesome-avs/
          DOCKERS_HOST=localhost devkit avs devnet start --skip-avs-run
          sleep 10

      - name: Check devnet RPC is live
        run: |
          for i in {1..10}; do
            bn=$(cast block-number --rpc-url http://localhost:8545 || echo "error")
            if [ "$bn" != "error" ]; then
              echo "Current block number: $bn"
              exit 0
            fi
            echo "Waiting for devnet... retrying in 2s"
            sleep 2
          done
          echo "❌ Devnet failed to start"
          exit 1

      - name: Stop devnet
        run: |
          cd ./my-awesome-avs/
          devkit avs devnet stop