name: Devkit AVS Create Test

on:
  push:
    branches: [main]
  pull_request:
    branches: ["**"]

env:
  FOUNDRY_PROFILE: ci

jobs:
  e2e:
    strategy:
      fail-fast: true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly-1ae64e38a1c69bda45343947875f7c86bad00038

      - name: Install devkit CLI
        run: make install

      - name: Add ~/bin to PATH
        run: echo "$HOME/bin" >> $GITHUB_PATH

      - name: Configure Git to use GitHub token
        run: |
          git config --global url."https://${{ secrets.HOURGLASS_TOKEN }}:@github.com/".insteadOf "https://github.com/"
        
      - name: Run devkit avs create
        run: |
          devkit avs create my-awesome-avs
      - name: Verify AVS project created
        run: |
          if [ ! -f "$HOME/avs/my-awesome-avs/eigen.toml" ]; then
            echo "❌ AVS project eigen.toml not found!"
            exit 1
          fi
          echo "✅ AVS project created successfully at $HOME/avs/my-awesome-avs/"

      - name: Run devkit avs build
        run: |
          cd $HOME/avs/my-awesome-avs/
          devkit avs build 
      
      - name: Run devkit avs devnet start
        run: |
          devkit avs devnet start
          sleep 10 # wait for devnet to fully start
     
      - name: Check devnet is running correctly (with retry)
        run: |
          for i in {1..10}; do
            bn=$(cast block-number --rpc-url http://localhost:8545 || echo "error")
            if [ "$bn" != "error" ]; then
              echo "Current block number: $bn"
              exit 0
            fi
            echo "Anvil not ready yet, retrying in 2s..."
            sleep 2
          done
          echo "Devnet didn't start properly after waiting"
          exit 1        
    
      - name: Check devkit avs run
        run: |
            devkit avs run 
      
      - name: Devnet Stop
        run: |
            devkit avs devnet stop
          
    